# Site settings
title: Rubys, Rails, & Scripts 
header-img: img/home-bg.png
email: harleymteden@gmail.com
copyright_name: harleyharl
description: > # this means to ignore newlines until "baseurl:"
  slapping some code together 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  harleyharl
learn_profile: harleyharl
email_username: harleymteden@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
